# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 14:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.abstract.utils
import src.accounts.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number.', regex='^[0-9]{10}$'), django.core.validators.MinLengthValidator(10)])),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_joining', models.DateField(default=src.abstract.utils.today)),
                ('leaves_taken', models.PositiveIntegerField(blank=True, default=0)),
                ('halfday_leaves_taken', models.FloatField(blank=True, default=0.0)),
                ('initial_login', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='utils.Role')),
            ],
            options={
                'ordering': ('-id',),
            },
            managers=[
                ('objects', src.accounts.managers.AccountManager()),
            ],
        ),
    ]
