# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import src.abstract.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_on', models.DateField(default=src.abstract.utils.today)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('edited_on', models.DateField(auto_now=True)),
                ('code', models.CharField(default='A', max_length=1, unique=True)),
                ('desc', models.CharField(max_length=20)),
                ('payment_amount', models.PositiveIntegerField(default=0)),
                ('increment', models.PositiveIntegerField(default=0)),
                ('leave_limit', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
